@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Henri Storage" #F4F6F6{
Class "<<interface>>\nHenriStorage" as HenriStorage
Class JsonHenriStorage
Class JsonSerializableHenri
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" HenriStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> HenriStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHenriStorage .up.|> HenriStorage
JsonHenriStorage ..> JsonSerializableHenri
JsonSerializableHenri --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
