@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CreateTeamCommand" as CreateTeamCommand LOGIC_COLOR
participant ":Model" as Model LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueTeamList" as TeamList MODEL_COLOR
end box

[-> LogicManager : <<create>>(model, storage)
activate LogicManager

LogicManager -> Model : getAddressBook()
activate Model

Model --> LogicManager : addressBook
deactivate Model

LogicManager -> AddressBook : getTeamList()
activate AddressBook

AddressBook --> LogicManager : teamList
deactivate AddressBook

LogicManager -> LogicManager : findMaxTeamId(teamList)
activate LogicManager

LogicManager --> LogicManager : maxTeamId
deactivate LogicManager

LogicManager -> CreateTeamCommand : setNextId(maxTeamId + 1)
activate CreateTeamCommand

CreateTeamCommand --> LogicManager
deactivate CreateTeamCommand

[<-- LogicManager
deactivate LogicManager

...

[-> CreateTeamCommand : execute(model)
activate CreateTeamCommand

CreateTeamCommand -> CreateTeamCommand : getAndIncrementNextId()
activate CreateTeamCommand


CreateTeamCommand --> CreateTeamCommand : teamId
deactivate CreateTeamCommand

CreateTeamCommand -> CreateTeamCommand : createTeam(teamId)
activate CreateTeamCommand

CreateTeamCommand --> CreateTeamCommand : team
deactivate CreateTeamCommand

CreateTeamCommand -> Model : addTeam(team)
activate Model

Model -> AddressBook : addTeam(team)
activate AddressBook

AddressBook -> TeamList : add(team)
activate TeamList

TeamList --> AddressBook
deactivate TeamList

AddressBook --> Model
deactivate AddressBook

Model --> CreateTeamCommand
deactivate Model

[<-- CreateTeamCommand : CommandResult
deactivate CreateTeamCommand

@enduml
