@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedHenri" as VersionedHenri MODEL_COLOR
end box

[-> Model : undoHenri()
activate Model

Model -> VersionedHenri : undo()
activate VersionedHenri

VersionedHenri -> VersionedHenri :resetData(ReadOnlyHenri)
VersionedHenri --> Model :
deactivate VersionedHenri

[<-- Model
deactivate Model

@enduml
