@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "parser:AddCommandParser" as Parser LOGIC_COLOR
participant "cmd:AddCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
end box

[-> LogicManager : execute("add -name John...")
note right: Ommit other details in the command for better readability

activate LogicManager

LogicManager -> Parser ** : create()
LogicManager -> Parser : parse(args)
activate Parser

Parser -> Model : getAddressBook()
activate Model
Model --> Parser : addressBook
deactivate Model

Parser -> AddressBook : getPersonList()
activate AddressBook
AddressBook --> Parser : persons
deactivate AddressBook

Parser -> Parser : extractUsedIds(persons)
activate Parser
Parser --> Parser : usedIds (Set<Long>)
deactivate Parser

Parser -> Parser : findNextAvailableId(usedIds)
activate Parser
Parser --> Parser : newId (e.g., 1)
deactivate Parser

Parser -> Parser : formatEmployeeId(newId)
activate Parser
Parser --> Parser : employeeId
deactivate Parser

Parser -> AddCommand ** : create(employeeId, person)
Parser --> LogicManager : addCommand
deactivate Parser

LogicManager -> AddCommand : execute(model)
activate AddCommand

AddCommand -> Model : addPerson(person)
activate Model
Model --> AddCommand
deactivate Model

AddCommand --> LogicManager : commandResult
deactivate AddCommand

[<-- LogicManager
deactivate LogicManager

@enduml
